import = ["/home/tsousa/.config/alacritty/themes/catppuccin/catppuccin-macchiato.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.95
padding = { x = 0, y = 5 }
